version: '3'

services:
  database:
    image: ghcr.io/hardingadonis/miu-shop-database:1.0.0
    ports:
      - "3306:3306"
  
  server:
    image: ghcr.io/hardingadonis/miu-shop-server:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - database