version: '3'

name: 'miu'

services:
  database:
    image: ghcr.io/hardingadonis/miu-shop-database:latest
    ports:
      - "3306:3306"
  
  server:
    image: ghcr.io/hardingadonis/miu-shop-server:latest
    ports:
      - "80:8080"
    depends_on:
      - database