name: 'Publish Miu Shop Images'

on:
  workflow_run:
    workflows: [Release Miu Shop]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: 'Publish Miu Shop Images'
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: 'x64'
      
      - name: 'Build project with Maven'
        run: |
          mvn verify
      
      - name: 'Get version'
        id: get_version
        run: |
          chmod +x get_version.sh
          echo "version=$(./get_version.sh)" >> $GITHUB_OUTPUT
      
      - name: 'Login ghcr.io'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Publish Miu Shop Database'
        working-directory: ${{ github.workspace }}/database
        run: |
          docker build . -t ghcr.io/hardingadonis/miu-shop-database:${{ steps.get_version.outputs.version }} -t ghcr.io/hardingadonis/miu-shop-database:latest
          docker push ghcr.io/hardingadonis/miu-shop-database:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/hardingadonis/miu-shop-database:latest
      
      - name: 'Publish Miu Shop Server'
        working-directory: ${{ github.workspace }}/server
        run: |
          docker build . -t ghcr.io/hardingadonis/miu-shop-server:${{ steps.get_version.outputs.version }} -t ghcr.io/hardingadonis/miu-shop-server:latest
          docker push ghcr.io/hardingadonis/miu-shop-server:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/hardingadonis/miu-shop-server:latest